spring:
  datasource:
    url: jdbc:h2:mem:credit-request-system-db
    username: ${db_username}
    password: ${db_password}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow_others: false
