spring:
  datasource:
    url: jdbc:h2:mem:credit-request-system-db
    username: ${db_username}
    password: ${db_password}
  jpa:
#      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow_others: false
